version: "2"
checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  file-lines:
    enabled: true
    config:
      threshold: 300
  method-complexity:
    enabled: false
  method-count:
    enabled: true
    config:
      threshold: 10
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: false
  identical-code:
    enabled: true
    config:
      threshold: 12

exclude_patterns:
- "node_modules/"
- "dist/"
- "build/"
- "package-lock.json"
- ".husky/*"
- ".husky"
- ".github"
- ".github/*"
- "src/tests/*"